### ISSUE TITLE
Could you possibly support Microsoft.EntityFrameworkCore 5.0.3?

### ISSUE THREAD

**Issue by multinerd** [Rwing/EntityFrameworkCore.UseRowNumberForPaging#1]
See title. Reason being we use AspNetZero and dont want to change too much of the core project.

**Comment by multinerd** [comment]
Actually, nvm. I can just dump the 2 files in my project and be done with it. Thanks for creating this lib in the first place.

**Comment by Rwing** [comment]
yep! It's my mistake that it only supports version 5.0.5.
I'll downgrade it to support 5.0 asap.

**Comment by Rwing** [comment]
done
