### ISSUE TITLE
net 9 version?

### ISSUE THREAD

**Issue by aspmaker** [Rwing/EntityFrameworkCore.UseRowNumberForPaging#14]
Hello, do you have a plan for adding net 9 version? Thank you.

**Comment by funkysi1701** [comment]
.Net 9 isn't released until November. I am sure after it is released we will get a new version

**Comment by aspmaker** [comment]
Sorry i don't know so i want to ask, why we need to wait for release? Isn't the preview enough?

**Comment by yltsa** [comment]
Hi, .NET9 was released yesterday.. :-)

**Comment by vipwan** [comment]
> Hello, do you have a plan for adding net 9 version? Thank you.

https://github.com/vipwan/Biwen.EFCore.UseRowNumberForPaging

**Comment by Rwing** [comment]
I will support .NET 9 as soon as possible, but since I have limited free time recently, contributions via PR are also welcome.

**Comment by yltsa** [comment]
Hi, not sure if your code is base for this. .NET9 works in my application:

https://github.com/vipwan/Biwen.EFCore.UseRowNumberForPaging

**Comment by Rwing** [comment]
The new version has been released, thank you all
