### ISSUE TITLE
.net 6 + ef 6.0.5 Errors will still be reported

### ISSUE THREAD

**Issue by dykRiver** [Rwing/EntityFrameworkCore.UseRowNumberForPaging#15]
.net 6 + ef 6.0.5
In the case of navigation attributes，one-to-many，.Include(x => x.Products)，Errors will still be reported，
Microsoft.Data.SqlClient.SqlException:“'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。”

**Comment by Rwing** [comment]
It seems to be the result of incorrect configuration. Please share your DbContext code
