### ISSUE TITLE
Exception thrown in dotnet 6.

### ISSUE THREAD

**Issue by william19941994** [Rwing/EntityFrameworkCore.UseRowNumberForPaging#2]
This project is excellent. It works fine with my project using SQL Server 2008 and dot net 5.
I upgrade to dot net 6 yestoday.
An exception was thrown. 
InvalidOperationException: SelectExpression.GenerateOuterColumn() is not found

**Comment by Rwing** [comment]
Thanks for your interest. I'll fix it ASAP.

**Comment by floydhamandi** [comment]
Any updates on .net 6 version

**Comment by Megasware128** [comment]
I fixed it with #3

**Comment by Megasware128** [comment]
Released in 0.3, can be closed

**Comment by Rwing** [comment]
Thank you @Megasware128 for making this contribution

**Comment by william19941994** [comment]
Thank you.
The new version did solved my prolem.
